/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef EnumTest_CONSTANTS_H
#define EnumTest_CONSTANTS_H

#include "EnumTest_types.h"



class EnumTestConstants {
 public:
  EnumTestConstants();

};

extern const EnumTestConstants g_EnumTest_constants;



#endif
