/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SecondService.h"
#include "thrift/async/TAsyncChannel.h"
#include "SecondService.tcc"

namespace thrift { namespace test {


SecondService_blahBlah_args::~SecondService_blahBlah_args() throw() {
}


SecondService_blahBlah_pargs::~SecondService_blahBlah_pargs() throw() {
}


SecondService_blahBlah_result::~SecondService_blahBlah_result() throw() {
}


SecondService_blahBlah_presult::~SecondService_blahBlah_presult() throw() {
}


SecondService_secondtestString_args::~SecondService_secondtestString_args() throw() {
}


SecondService_secondtestString_pargs::~SecondService_secondtestString_pargs() throw() {
}


SecondService_secondtestString_result::~SecondService_secondtestString_result() throw() {
}


SecondService_secondtestString_presult::~SecondService_secondtestString_presult() throw() {
}

}} // namespace

