/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftTest_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace thrift { namespace test {

int _kNumberzValues[] = {
  Numberz::ONE,
  Numberz::TWO,
  Numberz::THREE,
  Numberz::FIVE,
  Numberz::SIX,
  Numberz::EIGHT
};
const char* _kNumberzNames[] = {
  "ONE",
  "TWO",
  "THREE",
  "FIVE",
  "SIX",
  "EIGHT"
};
const std::map<int, const char*> _Numberz_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(6, _kNumberzValues, _kNumberzNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));


Bonk::~Bonk() throw() {
}


void Bonk::__set_message(const std::string& val) {
  this->message = val;
}

void Bonk::__set_type(const int32_t val) {
  this->type = val;
}

void swap(Bonk &a, Bonk &b) {
  using ::std::swap;
  swap(a.message, b.message);
  swap(a.type, b.type);
  swap(a.__isset, b.__isset);
}

Bonk::Bonk(const Bonk& other0) {
  message = other0.message;
  type = other0.type;
  __isset = other0.__isset;
}
Bonk& Bonk::operator=(const Bonk& other1) {
  message = other1.message;
  type = other1.type;
  __isset = other1.__isset;
  return *this;
}
void Bonk::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Bonk(";
  out << "message=" << to_string(message);
  out << ", " << "type=" << to_string(type);
  out << ")";
}


Bools::~Bools() throw() {
}


void Bools::__set_im_true(const bool val) {
  this->im_true = val;
}

void Bools::__set_im_false(const bool val) {
  this->im_false = val;
}

void swap(Bools &a, Bools &b) {
  using ::std::swap;
  swap(a.im_true, b.im_true);
  swap(a.im_false, b.im_false);
  swap(a.__isset, b.__isset);
}

Bools::Bools(const Bools& other2) {
  im_true = other2.im_true;
  im_false = other2.im_false;
  __isset = other2.__isset;
}
Bools& Bools::operator=(const Bools& other3) {
  im_true = other3.im_true;
  im_false = other3.im_false;
  __isset = other3.__isset;
  return *this;
}
void Bools::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Bools(";
  out << "im_true=" << to_string(im_true);
  out << ", " << "im_false=" << to_string(im_false);
  out << ")";
}


Xtruct::~Xtruct() throw() {
}


void Xtruct::__set_string_thing(const std::string& val) {
  this->string_thing = val;
}

void Xtruct::__set_byte_thing(const int8_t val) {
  this->byte_thing = val;
}

void Xtruct::__set_i32_thing(const int32_t val) {
  this->i32_thing = val;
}

void Xtruct::__set_i64_thing(const int64_t val) {
  this->i64_thing = val;
}

void swap(Xtruct &a, Xtruct &b) {
  using ::std::swap;
  swap(a.string_thing, b.string_thing);
  swap(a.byte_thing, b.byte_thing);
  swap(a.i32_thing, b.i32_thing);
  swap(a.i64_thing, b.i64_thing);
  swap(a.__isset, b.__isset);
}

Xtruct::Xtruct(const Xtruct& other4) {
  string_thing = other4.string_thing;
  byte_thing = other4.byte_thing;
  i32_thing = other4.i32_thing;
  i64_thing = other4.i64_thing;
  __isset = other4.__isset;
}
Xtruct& Xtruct::operator=(const Xtruct& other5) {
  string_thing = other5.string_thing;
  byte_thing = other5.byte_thing;
  i32_thing = other5.i32_thing;
  i64_thing = other5.i64_thing;
  __isset = other5.__isset;
  return *this;
}
void Xtruct::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Xtruct(";
  out << "string_thing=" << to_string(string_thing);
  out << ", " << "byte_thing=" << to_string(byte_thing);
  out << ", " << "i32_thing=" << to_string(i32_thing);
  out << ", " << "i64_thing=" << to_string(i64_thing);
  out << ")";
}


Xtruct2::~Xtruct2() throw() {
}


void Xtruct2::__set_byte_thing(const int8_t val) {
  this->byte_thing = val;
}

void Xtruct2::__set_struct_thing(const Xtruct& val) {
  this->struct_thing = val;
}

void Xtruct2::__set_i32_thing(const int32_t val) {
  this->i32_thing = val;
}

void swap(Xtruct2 &a, Xtruct2 &b) {
  using ::std::swap;
  swap(a.byte_thing, b.byte_thing);
  swap(a.struct_thing, b.struct_thing);
  swap(a.i32_thing, b.i32_thing);
  swap(a.__isset, b.__isset);
}

Xtruct2::Xtruct2(const Xtruct2& other6) {
  byte_thing = other6.byte_thing;
  struct_thing = other6.struct_thing;
  i32_thing = other6.i32_thing;
  __isset = other6.__isset;
}
Xtruct2& Xtruct2::operator=(const Xtruct2& other7) {
  byte_thing = other7.byte_thing;
  struct_thing = other7.struct_thing;
  i32_thing = other7.i32_thing;
  __isset = other7.__isset;
  return *this;
}
void Xtruct2::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Xtruct2(";
  out << "byte_thing=" << to_string(byte_thing);
  out << ", " << "struct_thing=" << to_string(struct_thing);
  out << ", " << "i32_thing=" << to_string(i32_thing);
  out << ")";
}


Xtruct3::~Xtruct3() throw() {
}


void Xtruct3::__set_string_thing(const std::string& val) {
  this->string_thing = val;
}

void Xtruct3::__set_changed(const int32_t val) {
  this->changed = val;
}

void Xtruct3::__set_i32_thing(const int32_t val) {
  this->i32_thing = val;
}

void Xtruct3::__set_i64_thing(const int64_t val) {
  this->i64_thing = val;
}

void swap(Xtruct3 &a, Xtruct3 &b) {
  using ::std::swap;
  swap(a.string_thing, b.string_thing);
  swap(a.changed, b.changed);
  swap(a.i32_thing, b.i32_thing);
  swap(a.i64_thing, b.i64_thing);
  swap(a.__isset, b.__isset);
}

Xtruct3::Xtruct3(const Xtruct3& other8) {
  string_thing = other8.string_thing;
  changed = other8.changed;
  i32_thing = other8.i32_thing;
  i64_thing = other8.i64_thing;
  __isset = other8.__isset;
}
Xtruct3& Xtruct3::operator=(const Xtruct3& other9) {
  string_thing = other9.string_thing;
  changed = other9.changed;
  i32_thing = other9.i32_thing;
  i64_thing = other9.i64_thing;
  __isset = other9.__isset;
  return *this;
}
void Xtruct3::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Xtruct3(";
  out << "string_thing=" << to_string(string_thing);
  out << ", " << "changed=" << to_string(changed);
  out << ", " << "i32_thing=" << to_string(i32_thing);
  out << ", " << "i64_thing=" << to_string(i64_thing);
  out << ")";
}


Insanity::~Insanity() throw() {
}


void Insanity::__set_userMap(const std::map<Numberz::type, UserId> & val) {
  this->userMap = val;
}

void Insanity::__set_xtructs(const std::vector<Xtruct> & val) {
  this->xtructs = val;
}

void swap(Insanity &a, Insanity &b) {
  using ::std::swap;
  swap(a.userMap, b.userMap);
  swap(a.xtructs, b.xtructs);
  swap(a.__isset, b.__isset);
}

Insanity::Insanity(const Insanity& other25) {
  userMap = other25.userMap;
  xtructs = other25.xtructs;
  __isset = other25.__isset;
}
Insanity& Insanity::operator=(const Insanity& other26) {
  userMap = other26.userMap;
  xtructs = other26.xtructs;
  __isset = other26.__isset;
  return *this;
}
void Insanity::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Insanity(";
  out << "userMap=" << to_string(userMap);
  out << ", " << "xtructs=" << to_string(xtructs);
  out << ")";
}


CrazyNesting::~CrazyNesting() throw() {
}


void CrazyNesting::__set_string_field(const std::string& val) {
  this->string_field = val;
}

void CrazyNesting::__set_set_field(const std::set<Insanity> & val) {
  this->set_field = val;
__isset.set_field = true;
}

void CrazyNesting::__set_list_field(const std::vector<std::map<std::set<int32_t> , std::map<int32_t, std::set<std::vector<std::map<Insanity, std::string> > > > > > & val) {
  this->list_field = val;
}

void CrazyNesting::__set_binary_field(const std::string& val) {
  this->binary_field = val;
}

void swap(CrazyNesting &a, CrazyNesting &b) {
  using ::std::swap;
  swap(a.string_field, b.string_field);
  swap(a.set_field, b.set_field);
  swap(a.list_field, b.list_field);
  swap(a.binary_field, b.binary_field);
  swap(a.__isset, b.__isset);
}

CrazyNesting::CrazyNesting(const CrazyNesting& other84) {
  string_field = other84.string_field;
  set_field = other84.set_field;
  list_field = other84.list_field;
  binary_field = other84.binary_field;
  __isset = other84.__isset;
}
CrazyNesting& CrazyNesting::operator=(const CrazyNesting& other85) {
  string_field = other85.string_field;
  set_field = other85.set_field;
  list_field = other85.list_field;
  binary_field = other85.binary_field;
  __isset = other85.__isset;
  return *this;
}
void CrazyNesting::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "CrazyNesting(";
  out << "string_field=" << to_string(string_field);
  out << ", " << "set_field="; (__isset.set_field ? (out << to_string(set_field)) : (out << "<null>"));
  out << ", " << "list_field=" << to_string(list_field);
  out << ", " << "binary_field=" << to_string(binary_field);
  out << ")";
}


Xception::~Xception() throw() {
}


void Xception::__set_errorCode(const int32_t val) {
  this->errorCode = val;
}

void Xception::__set_message(const std::string& val) {
  this->message = val;
}

void swap(Xception &a, Xception &b) {
  using ::std::swap;
  swap(a.errorCode, b.errorCode);
  swap(a.message, b.message);
  swap(a.__isset, b.__isset);
}

Xception::Xception(const Xception& other86) : TException() {
  errorCode = other86.errorCode;
  message = other86.message;
  __isset = other86.__isset;
}
Xception& Xception::operator=(const Xception& other87) {
  errorCode = other87.errorCode;
  message = other87.message;
  __isset = other87.__isset;
  return *this;
}
void Xception::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Xception(";
  out << "errorCode=" << to_string(errorCode);
  out << ", " << "message=" << to_string(message);
  out << ")";
}

const char* Xception::what() const throw() {
  try {
    std::stringstream ss;
    ss << "TException - service has thrown: " << *this;
    this->thriftTExceptionMessageHolder_ = ss.str();
    return this->thriftTExceptionMessageHolder_.c_str();
  } catch (const std::exception&) {
    return "TException - service has thrown: Xception";
  }
}


Xception2::~Xception2() throw() {
}


void Xception2::__set_errorCode(const int32_t val) {
  this->errorCode = val;
}

void Xception2::__set_struct_thing(const Xtruct& val) {
  this->struct_thing = val;
}

void swap(Xception2 &a, Xception2 &b) {
  using ::std::swap;
  swap(a.errorCode, b.errorCode);
  swap(a.struct_thing, b.struct_thing);
  swap(a.__isset, b.__isset);
}

Xception2::Xception2(const Xception2& other88) : TException() {
  errorCode = other88.errorCode;
  struct_thing = other88.struct_thing;
  __isset = other88.__isset;
}
Xception2& Xception2::operator=(const Xception2& other89) {
  errorCode = other89.errorCode;
  struct_thing = other89.struct_thing;
  __isset = other89.__isset;
  return *this;
}
void Xception2::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Xception2(";
  out << "errorCode=" << to_string(errorCode);
  out << ", " << "struct_thing=" << to_string(struct_thing);
  out << ")";
}

const char* Xception2::what() const throw() {
  try {
    std::stringstream ss;
    ss << "TException - service has thrown: " << *this;
    this->thriftTExceptionMessageHolder_ = ss.str();
    return this->thriftTExceptionMessageHolder_.c_str();
  } catch (const std::exception&) {
    return "TException - service has thrown: Xception2";
  }
}


EmptyStruct::~EmptyStruct() throw() {
}


void swap(EmptyStruct &a, EmptyStruct &b) {
  using ::std::swap;
  (void) a;
  (void) b;
}

EmptyStruct::EmptyStruct(const EmptyStruct& other90) {
  (void) other90;
}
EmptyStruct& EmptyStruct::operator=(const EmptyStruct& other91) {
  (void) other91;
  return *this;
}
void EmptyStruct::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "EmptyStruct(";
  out << ")";
}


OneField::~OneField() throw() {
}


void OneField::__set_field(const EmptyStruct& val) {
  this->field = val;
}

void swap(OneField &a, OneField &b) {
  using ::std::swap;
  swap(a.field, b.field);
  swap(a.__isset, b.__isset);
}

OneField::OneField(const OneField& other92) {
  field = other92.field;
  __isset = other92.__isset;
}
OneField& OneField::operator=(const OneField& other93) {
  field = other93.field;
  __isset = other93.__isset;
  return *this;
}
void OneField::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "OneField(";
  out << "field=" << to_string(field);
  out << ")";
}


VersioningTestV1::~VersioningTestV1() throw() {
}


void VersioningTestV1::__set_begin_in_both(const int32_t val) {
  this->begin_in_both = val;
}

void VersioningTestV1::__set_old_string(const std::string& val) {
  this->old_string = val;
}

void VersioningTestV1::__set_end_in_both(const int32_t val) {
  this->end_in_both = val;
}

void swap(VersioningTestV1 &a, VersioningTestV1 &b) {
  using ::std::swap;
  swap(a.begin_in_both, b.begin_in_both);
  swap(a.old_string, b.old_string);
  swap(a.end_in_both, b.end_in_both);
  swap(a.__isset, b.__isset);
}

VersioningTestV1::VersioningTestV1(const VersioningTestV1& other94) {
  begin_in_both = other94.begin_in_both;
  old_string = other94.old_string;
  end_in_both = other94.end_in_both;
  __isset = other94.__isset;
}
VersioningTestV1& VersioningTestV1::operator=(const VersioningTestV1& other95) {
  begin_in_both = other95.begin_in_both;
  old_string = other95.old_string;
  end_in_both = other95.end_in_both;
  __isset = other95.__isset;
  return *this;
}
void VersioningTestV1::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "VersioningTestV1(";
  out << "begin_in_both=" << to_string(begin_in_both);
  out << ", " << "old_string=" << to_string(old_string);
  out << ", " << "end_in_both=" << to_string(end_in_both);
  out << ")";
}


VersioningTestV2::~VersioningTestV2() throw() {
}


void VersioningTestV2::__set_begin_in_both(const int32_t val) {
  this->begin_in_both = val;
}

void VersioningTestV2::__set_newint(const int32_t val) {
  this->newint = val;
}

void VersioningTestV2::__set_newbyte(const int8_t val) {
  this->newbyte = val;
}

void VersioningTestV2::__set_newshort(const int16_t val) {
  this->newshort = val;
}

void VersioningTestV2::__set_newlong(const int64_t val) {
  this->newlong = val;
}

void VersioningTestV2::__set_newdouble(const double val) {
  this->newdouble = val;
}

void VersioningTestV2::__set_newstruct(const Bonk& val) {
  this->newstruct = val;
}

void VersioningTestV2::__set_newlist(const std::vector<int32_t> & val) {
  this->newlist = val;
}

void VersioningTestV2::__set_newset(const std::set<int32_t> & val) {
  this->newset = val;
}

void VersioningTestV2::__set_newmap(const std::map<int32_t, int32_t> & val) {
  this->newmap = val;
}

void VersioningTestV2::__set_newstring(const std::string& val) {
  this->newstring = val;
}

void VersioningTestV2::__set_end_in_both(const int32_t val) {
  this->end_in_both = val;
}

void swap(VersioningTestV2 &a, VersioningTestV2 &b) {
  using ::std::swap;
  swap(a.begin_in_both, b.begin_in_both);
  swap(a.newint, b.newint);
  swap(a.newbyte, b.newbyte);
  swap(a.newshort, b.newshort);
  swap(a.newlong, b.newlong);
  swap(a.newdouble, b.newdouble);
  swap(a.newstruct, b.newstruct);
  swap(a.newlist, b.newlist);
  swap(a.newset, b.newset);
  swap(a.newmap, b.newmap);
  swap(a.newstring, b.newstring);
  swap(a.end_in_both, b.end_in_both);
  swap(a.__isset, b.__isset);
}

VersioningTestV2::VersioningTestV2(const VersioningTestV2& other117) {
  begin_in_both = other117.begin_in_both;
  newint = other117.newint;
  newbyte = other117.newbyte;
  newshort = other117.newshort;
  newlong = other117.newlong;
  newdouble = other117.newdouble;
  newstruct = other117.newstruct;
  newlist = other117.newlist;
  newset = other117.newset;
  newmap = other117.newmap;
  newstring = other117.newstring;
  end_in_both = other117.end_in_both;
  __isset = other117.__isset;
}
VersioningTestV2& VersioningTestV2::operator=(const VersioningTestV2& other118) {
  begin_in_both = other118.begin_in_both;
  newint = other118.newint;
  newbyte = other118.newbyte;
  newshort = other118.newshort;
  newlong = other118.newlong;
  newdouble = other118.newdouble;
  newstruct = other118.newstruct;
  newlist = other118.newlist;
  newset = other118.newset;
  newmap = other118.newmap;
  newstring = other118.newstring;
  end_in_both = other118.end_in_both;
  __isset = other118.__isset;
  return *this;
}
void VersioningTestV2::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "VersioningTestV2(";
  out << "begin_in_both=" << to_string(begin_in_both);
  out << ", " << "newint=" << to_string(newint);
  out << ", " << "newbyte=" << to_string(newbyte);
  out << ", " << "newshort=" << to_string(newshort);
  out << ", " << "newlong=" << to_string(newlong);
  out << ", " << "newdouble=" << to_string(newdouble);
  out << ", " << "newstruct=" << to_string(newstruct);
  out << ", " << "newlist=" << to_string(newlist);
  out << ", " << "newset=" << to_string(newset);
  out << ", " << "newmap=" << to_string(newmap);
  out << ", " << "newstring=" << to_string(newstring);
  out << ", " << "end_in_both=" << to_string(end_in_both);
  out << ")";
}


ListTypeVersioningV1::~ListTypeVersioningV1() throw() {
}


void ListTypeVersioningV1::__set_myints(const std::vector<int32_t> & val) {
  this->myints = val;
}

void ListTypeVersioningV1::__set_hello(const std::string& val) {
  this->hello = val;
}

void swap(ListTypeVersioningV1 &a, ListTypeVersioningV1 &b) {
  using ::std::swap;
  swap(a.myints, b.myints);
  swap(a.hello, b.hello);
  swap(a.__isset, b.__isset);
}

ListTypeVersioningV1::ListTypeVersioningV1(const ListTypeVersioningV1& other125) {
  myints = other125.myints;
  hello = other125.hello;
  __isset = other125.__isset;
}
ListTypeVersioningV1& ListTypeVersioningV1::operator=(const ListTypeVersioningV1& other126) {
  myints = other126.myints;
  hello = other126.hello;
  __isset = other126.__isset;
  return *this;
}
void ListTypeVersioningV1::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ListTypeVersioningV1(";
  out << "myints=" << to_string(myints);
  out << ", " << "hello=" << to_string(hello);
  out << ")";
}


ListTypeVersioningV2::~ListTypeVersioningV2() throw() {
}


void ListTypeVersioningV2::__set_strings(const std::vector<std::string> & val) {
  this->strings = val;
}

void ListTypeVersioningV2::__set_hello(const std::string& val) {
  this->hello = val;
}

void swap(ListTypeVersioningV2 &a, ListTypeVersioningV2 &b) {
  using ::std::swap;
  swap(a.strings, b.strings);
  swap(a.hello, b.hello);
  swap(a.__isset, b.__isset);
}

ListTypeVersioningV2::ListTypeVersioningV2(const ListTypeVersioningV2& other133) {
  strings = other133.strings;
  hello = other133.hello;
  __isset = other133.__isset;
}
ListTypeVersioningV2& ListTypeVersioningV2::operator=(const ListTypeVersioningV2& other134) {
  strings = other134.strings;
  hello = other134.hello;
  __isset = other134.__isset;
  return *this;
}
void ListTypeVersioningV2::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ListTypeVersioningV2(";
  out << "strings=" << to_string(strings);
  out << ", " << "hello=" << to_string(hello);
  out << ")";
}


GuessProtocolStruct::~GuessProtocolStruct() throw() {
}


void GuessProtocolStruct::__set_map_field(const std::map<std::string, std::string> & val) {
  this->map_field = val;
}

void swap(GuessProtocolStruct &a, GuessProtocolStruct &b) {
  using ::std::swap;
  swap(a.map_field, b.map_field);
  swap(a.__isset, b.__isset);
}

GuessProtocolStruct::GuessProtocolStruct(const GuessProtocolStruct& other143) {
  map_field = other143.map_field;
  __isset = other143.__isset;
}
GuessProtocolStruct& GuessProtocolStruct::operator=(const GuessProtocolStruct& other144) {
  map_field = other144.map_field;
  __isset = other144.__isset;
  return *this;
}
void GuessProtocolStruct::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "GuessProtocolStruct(";
  out << "map_field=" << to_string(map_field);
  out << ")";
}


LargeDeltas::~LargeDeltas() throw() {
}


void LargeDeltas::__set_b1(const Bools& val) {
  this->b1 = val;
}

void LargeDeltas::__set_b10(const Bools& val) {
  this->b10 = val;
}

void LargeDeltas::__set_b100(const Bools& val) {
  this->b100 = val;
}

void LargeDeltas::__set_check_true(const bool val) {
  this->check_true = val;
}

void LargeDeltas::__set_b1000(const Bools& val) {
  this->b1000 = val;
}

void LargeDeltas::__set_check_false(const bool val) {
  this->check_false = val;
}

void LargeDeltas::__set_vertwo2000(const VersioningTestV2& val) {
  this->vertwo2000 = val;
}

void LargeDeltas::__set_a_set2500(const std::set<std::string> & val) {
  this->a_set2500 = val;
}

void LargeDeltas::__set_vertwo3000(const VersioningTestV2& val) {
  this->vertwo3000 = val;
}

void LargeDeltas::__set_big_numbers(const std::vector<int32_t> & val) {
  this->big_numbers = val;
}

void swap(LargeDeltas &a, LargeDeltas &b) {
  using ::std::swap;
  swap(a.b1, b.b1);
  swap(a.b10, b.b10);
  swap(a.b100, b.b100);
  swap(a.check_true, b.check_true);
  swap(a.b1000, b.b1000);
  swap(a.check_false, b.check_false);
  swap(a.vertwo2000, b.vertwo2000);
  swap(a.a_set2500, b.a_set2500);
  swap(a.vertwo3000, b.vertwo3000);
  swap(a.big_numbers, b.big_numbers);
  swap(a.__isset, b.__isset);
}

LargeDeltas::LargeDeltas(const LargeDeltas& other158) {
  b1 = other158.b1;
  b10 = other158.b10;
  b100 = other158.b100;
  check_true = other158.check_true;
  b1000 = other158.b1000;
  check_false = other158.check_false;
  vertwo2000 = other158.vertwo2000;
  a_set2500 = other158.a_set2500;
  vertwo3000 = other158.vertwo3000;
  big_numbers = other158.big_numbers;
  __isset = other158.__isset;
}
LargeDeltas& LargeDeltas::operator=(const LargeDeltas& other159) {
  b1 = other159.b1;
  b10 = other159.b10;
  b100 = other159.b100;
  check_true = other159.check_true;
  b1000 = other159.b1000;
  check_false = other159.check_false;
  vertwo2000 = other159.vertwo2000;
  a_set2500 = other159.a_set2500;
  vertwo3000 = other159.vertwo3000;
  big_numbers = other159.big_numbers;
  __isset = other159.__isset;
  return *this;
}
void LargeDeltas::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LargeDeltas(";
  out << "b1=" << to_string(b1);
  out << ", " << "b10=" << to_string(b10);
  out << ", " << "b100=" << to_string(b100);
  out << ", " << "check_true=" << to_string(check_true);
  out << ", " << "b1000=" << to_string(b1000);
  out << ", " << "check_false=" << to_string(check_false);
  out << ", " << "vertwo2000=" << to_string(vertwo2000);
  out << ", " << "a_set2500=" << to_string(a_set2500);
  out << ", " << "vertwo3000=" << to_string(vertwo3000);
  out << ", " << "big_numbers=" << to_string(big_numbers);
  out << ")";
}


NestedListsI32x2::~NestedListsI32x2() throw() {
}


void NestedListsI32x2::__set_integerlist(const std::vector<std::vector<int32_t> > & val) {
  this->integerlist = val;
}

void swap(NestedListsI32x2 &a, NestedListsI32x2 &b) {
  using ::std::swap;
  swap(a.integerlist, b.integerlist);
  swap(a.__isset, b.__isset);
}

NestedListsI32x2::NestedListsI32x2(const NestedListsI32x2& other172) {
  integerlist = other172.integerlist;
  __isset = other172.__isset;
}
NestedListsI32x2& NestedListsI32x2::operator=(const NestedListsI32x2& other173) {
  integerlist = other173.integerlist;
  __isset = other173.__isset;
  return *this;
}
void NestedListsI32x2::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "NestedListsI32x2(";
  out << "integerlist=" << to_string(integerlist);
  out << ")";
}


NestedListsI32x3::~NestedListsI32x3() throw() {
}


void NestedListsI32x3::__set_integerlist(const std::vector<std::vector<std::vector<int32_t> > > & val) {
  this->integerlist = val;
}

void swap(NestedListsI32x3 &a, NestedListsI32x3 &b) {
  using ::std::swap;
  swap(a.integerlist, b.integerlist);
  swap(a.__isset, b.__isset);
}

NestedListsI32x3::NestedListsI32x3(const NestedListsI32x3& other192) {
  integerlist = other192.integerlist;
  __isset = other192.__isset;
}
NestedListsI32x3& NestedListsI32x3::operator=(const NestedListsI32x3& other193) {
  integerlist = other193.integerlist;
  __isset = other193.__isset;
  return *this;
}
void NestedListsI32x3::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "NestedListsI32x3(";
  out << "integerlist=" << to_string(integerlist);
  out << ")";
}


NestedMixedx2::~NestedMixedx2() throw() {
}


void NestedMixedx2::__set_int_set_list(const std::vector<std::set<int32_t> > & val) {
  this->int_set_list = val;
}

void NestedMixedx2::__set_map_int_strset(const std::map<int32_t, std::set<std::string> > & val) {
  this->map_int_strset = val;
}

void NestedMixedx2::__set_map_int_strset_list(const std::vector<std::map<int32_t, std::set<std::string> > > & val) {
  this->map_int_strset_list = val;
}

void swap(NestedMixedx2 &a, NestedMixedx2 &b) {
  using ::std::swap;
  swap(a.int_set_list, b.int_set_list);
  swap(a.map_int_strset, b.map_int_strset);
  swap(a.map_int_strset_list, b.map_int_strset_list);
  swap(a.__isset, b.__isset);
}

NestedMixedx2::NestedMixedx2(const NestedMixedx2& other243) {
  int_set_list = other243.int_set_list;
  map_int_strset = other243.map_int_strset;
  map_int_strset_list = other243.map_int_strset_list;
  __isset = other243.__isset;
}
NestedMixedx2& NestedMixedx2::operator=(const NestedMixedx2& other244) {
  int_set_list = other244.int_set_list;
  map_int_strset = other244.map_int_strset;
  map_int_strset_list = other244.map_int_strset_list;
  __isset = other244.__isset;
  return *this;
}
void NestedMixedx2::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "NestedMixedx2(";
  out << "int_set_list=" << to_string(int_set_list);
  out << ", " << "map_int_strset=" << to_string(map_int_strset);
  out << ", " << "map_int_strset_list=" << to_string(map_int_strset_list);
  out << ")";
}


ListBonks::~ListBonks() throw() {
}


void ListBonks::__set_bonk(const std::vector<Bonk> & val) {
  this->bonk = val;
}

void swap(ListBonks &a, ListBonks &b) {
  using ::std::swap;
  swap(a.bonk, b.bonk);
  swap(a.__isset, b.__isset);
}

ListBonks::ListBonks(const ListBonks& other251) {
  bonk = other251.bonk;
  __isset = other251.__isset;
}
ListBonks& ListBonks::operator=(const ListBonks& other252) {
  bonk = other252.bonk;
  __isset = other252.__isset;
  return *this;
}
void ListBonks::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ListBonks(";
  out << "bonk=" << to_string(bonk);
  out << ")";
}


NestedListsBonk::~NestedListsBonk() throw() {
}


void NestedListsBonk::__set_bonk(const std::vector<std::vector<std::vector<Bonk> > > & val) {
  this->bonk = val;
}

void swap(NestedListsBonk &a, NestedListsBonk &b) {
  using ::std::swap;
  swap(a.bonk, b.bonk);
  swap(a.__isset, b.__isset);
}

NestedListsBonk::NestedListsBonk(const NestedListsBonk& other271) {
  bonk = other271.bonk;
  __isset = other271.__isset;
}
NestedListsBonk& NestedListsBonk::operator=(const NestedListsBonk& other272) {
  bonk = other272.bonk;
  __isset = other272.__isset;
  return *this;
}
void NestedListsBonk::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "NestedListsBonk(";
  out << "bonk=" << to_string(bonk);
  out << ")";
}


BoolTest::~BoolTest() throw() {
}


void BoolTest::__set_b(const bool val) {
  this->b = val;
__isset.b = true;
}

void BoolTest::__set_s(const std::string& val) {
  this->s = val;
__isset.s = true;
}

void swap(BoolTest &a, BoolTest &b) {
  using ::std::swap;
  swap(a.b, b.b);
  swap(a.s, b.s);
  swap(a.__isset, b.__isset);
}

BoolTest::BoolTest(const BoolTest& other273) {
  b = other273.b;
  s = other273.s;
  __isset = other273.__isset;
}
BoolTest& BoolTest::operator=(const BoolTest& other274) {
  b = other274.b;
  s = other274.s;
  __isset = other274.__isset;
  return *this;
}
void BoolTest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "BoolTest(";
  out << "b="; (__isset.b ? (out << to_string(b)) : (out << "<null>"));
  out << ", " << "s="; (__isset.s ? (out << to_string(s)) : (out << "<null>"));
  out << ")";
}


StructA::~StructA() throw() {
}


void StructA::__set_s(const std::string& val) {
  this->s = val;
}

void swap(StructA &a, StructA &b) {
  using ::std::swap;
  swap(a.s, b.s);
}

StructA::StructA(const StructA& other275) {
  s = other275.s;
}
StructA& StructA::operator=(const StructA& other276) {
  s = other276.s;
  return *this;
}
void StructA::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "StructA(";
  out << "s=" << to_string(s);
  out << ")";
}


StructB::~StructB() throw() {
}


void StructB::__set_aa(const StructA& val) {
  this->aa = val;
__isset.aa = true;
}

void StructB::__set_ab(const StructA& val) {
  this->ab = val;
}

void swap(StructB &a, StructB &b) {
  using ::std::swap;
  swap(a.aa, b.aa);
  swap(a.ab, b.ab);
  swap(a.__isset, b.__isset);
}

StructB::StructB(const StructB& other277) {
  aa = other277.aa;
  ab = other277.ab;
  __isset = other277.__isset;
}
StructB& StructB::operator=(const StructB& other278) {
  aa = other278.aa;
  ab = other278.ab;
  __isset = other278.__isset;
  return *this;
}
void StructB::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "StructB(";
  out << "aa="; (__isset.aa ? (out << to_string(aa)) : (out << "<null>"));
  out << ", " << "ab=" << to_string(ab);
  out << ")";
}

}} // namespace
