/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include <math.h>

#include "shared_types.h"
#include <thrift/c_glib/thrift.h>

enum _SharedStructProperties
{
  PROP_SHARED_STRUCT_0,
  PROP_SHARED_STRUCT_KEY,
  PROP_SHARED_STRUCT_VALUE
};

/* reads a shared_struct object */
static gint32
shared_struct_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  SharedStruct * this_object = SHARED_STRUCT(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_I32)
        {
          if ((ret = thrift_protocol_read_i32 (protocol, &this_object->key, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_key = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 2:
        if (ftype == T_STRING)
        {
          if (this_object->value != NULL)
          {
            g_free(this_object->value);
            this_object->value = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->value, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_value = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
shared_struct_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  SharedStruct * this_object = SHARED_STRUCT(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "SharedStruct", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "key", T_I32, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i32 (protocol, this_object->key, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "value", T_STRING, 2, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->value, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
shared_struct_set_property (GObject *object,
                            guint property_id,
                            const GValue *value,
                            GParamSpec *pspec)
{
  SharedStruct *self = SHARED_STRUCT (object);

  switch (property_id)
  {
    case PROP_SHARED_STRUCT_KEY:
      self->key = g_value_get_int (value);
      self->__isset_key = TRUE;
      break;

    case PROP_SHARED_STRUCT_VALUE:
      if (self->value != NULL)
        g_free (self->value);
      self->value = g_value_dup_string (value);
      self->__isset_value = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
shared_struct_get_property (GObject *object,
                            guint property_id,
                            GValue *value,
                            GParamSpec *pspec)
{
  SharedStruct *self = SHARED_STRUCT (object);

  switch (property_id)
  {
    case PROP_SHARED_STRUCT_KEY:
      g_value_set_int (value, self->key);
      break;

    case PROP_SHARED_STRUCT_VALUE:
      g_value_set_string (value, self->value);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
shared_struct_instance_init (SharedStruct * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->key = 0;
  object->__isset_key = FALSE;
  object->value = NULL;
  object->__isset_value = FALSE;
}

static void 
shared_struct_finalize (GObject *object)
{
  SharedStruct *tobject = SHARED_STRUCT (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->value != NULL)
  {
    g_free(tobject->value);
    tobject->value = NULL;
  }
}

static void
shared_struct_class_init (SharedStructClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = shared_struct_read;
  struct_class->write = shared_struct_write;

  gobject_class->finalize = shared_struct_finalize;
  gobject_class->get_property = shared_struct_get_property;
  gobject_class->set_property = shared_struct_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_SHARED_STRUCT_KEY,
     g_param_spec_int ("key",
                       NULL,
                       NULL,
                       G_MININT32,
                       G_MAXINT32,
                       0,
                       G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_SHARED_STRUCT_VALUE,
     g_param_spec_string ("value",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));
}

GType
shared_struct_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (SharedStructClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) shared_struct_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (SharedStruct),
      0, /* n_preallocs */
      (GInstanceInitFunc) shared_struct_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "SharedStructType",
                                   &type_info, 0);
  }

  return type;
}

/* constants */

enum _SharedServiceGetStructArgsProperties
{
  PROP_SHARED_SERVICE_GET_STRUCT_ARGS_0,
  PROP_SHARED_SERVICE_GET_STRUCT_ARGS_KEY
};

/* reads a shared_service_get_struct_args object */
static gint32
shared_service_get_struct_args_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  SharedServiceGetStructArgs * this_object = SHARED_SERVICE_GET_STRUCT_ARGS(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_I32)
        {
          if ((ret = thrift_protocol_read_i32 (protocol, &this_object->key, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_key = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
shared_service_get_struct_args_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  SharedServiceGetStructArgs * this_object = SHARED_SERVICE_GET_STRUCT_ARGS(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "SharedServiceGetStructArgs", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "key", T_I32, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i32 (protocol, this_object->key, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
shared_service_get_struct_args_set_property (GObject *object,
                                             guint property_id,
                                             const GValue *value,
                                             GParamSpec *pspec)
{
  SharedServiceGetStructArgs *self = SHARED_SERVICE_GET_STRUCT_ARGS (object);

  switch (property_id)
  {
    case PROP_SHARED_SERVICE_GET_STRUCT_ARGS_KEY:
      self->key = g_value_get_int (value);
      self->__isset_key = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
shared_service_get_struct_args_get_property (GObject *object,
                                             guint property_id,
                                             GValue *value,
                                             GParamSpec *pspec)
{
  SharedServiceGetStructArgs *self = SHARED_SERVICE_GET_STRUCT_ARGS (object);

  switch (property_id)
  {
    case PROP_SHARED_SERVICE_GET_STRUCT_ARGS_KEY:
      g_value_set_int (value, self->key);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
shared_service_get_struct_args_instance_init (SharedServiceGetStructArgs * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->key = 0;
  object->__isset_key = FALSE;
}

static void 
shared_service_get_struct_args_finalize (GObject *object)
{
  SharedServiceGetStructArgs *tobject = SHARED_SERVICE_GET_STRUCT_ARGS (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
}

static void
shared_service_get_struct_args_class_init (SharedServiceGetStructArgsClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = shared_service_get_struct_args_read;
  struct_class->write = shared_service_get_struct_args_write;

  gobject_class->finalize = shared_service_get_struct_args_finalize;
  gobject_class->get_property = shared_service_get_struct_args_get_property;
  gobject_class->set_property = shared_service_get_struct_args_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_SHARED_SERVICE_GET_STRUCT_ARGS_KEY,
     g_param_spec_int ("key",
                       NULL,
                       NULL,
                       G_MININT32,
                       G_MAXINT32,
                       0,
                       G_PARAM_READWRITE));
}

GType
shared_service_get_struct_args_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (SharedServiceGetStructArgsClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) shared_service_get_struct_args_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (SharedServiceGetStructArgs),
      0, /* n_preallocs */
      (GInstanceInitFunc) shared_service_get_struct_args_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "SharedServiceGetStructArgsType",
                                   &type_info, 0);
  }

  return type;
}

enum _SharedServiceGetStructResultProperties
{
  PROP_SHARED_SERVICE_GET_STRUCT_RESULT_0,
  PROP_SHARED_SERVICE_GET_STRUCT_RESULT_SUCCESS
};

/* reads a shared_service_get_struct_result object */
static gint32
shared_service_get_struct_result_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  SharedServiceGetStructResult * this_object = SHARED_SERVICE_GET_STRUCT_RESULT(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 0:
        if (ftype == T_STRUCT)
        {
          if ((ret = thrift_struct_read (THRIFT_STRUCT (this_object->success), protocol, error)) < 0)
          {
            return -1;
          }
          xfer += ret;
          this_object->__isset_success = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
shared_service_get_struct_result_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  SharedServiceGetStructResult * this_object = SHARED_SERVICE_GET_STRUCT_RESULT(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "SharedServiceGetStructResult", error)) < 0)
    return -1;
  xfer += ret;
  if (this_object->__isset_success == TRUE) {
    if ((ret = thrift_protocol_write_field_begin (protocol, "success", T_STRUCT, 0, error)) < 0)
      return -1;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (this_object->success), protocol, error)) < 0)
      return -1;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
shared_service_get_struct_result_set_property (GObject *object,
                                               guint property_id,
                                               const GValue *value,
                                               GParamSpec *pspec)
{
  SharedServiceGetStructResult *self = SHARED_SERVICE_GET_STRUCT_RESULT (object);

  switch (property_id)
  {
    case PROP_SHARED_SERVICE_GET_STRUCT_RESULT_SUCCESS:
      if (self->success != NULL)
        g_object_unref (self->success);
      self->success = g_value_dup_object (value);
      self->__isset_success = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
shared_service_get_struct_result_get_property (GObject *object,
                                               guint property_id,
                                               GValue *value,
                                               GParamSpec *pspec)
{
  SharedServiceGetStructResult *self = SHARED_SERVICE_GET_STRUCT_RESULT (object);

  switch (property_id)
  {
    case PROP_SHARED_SERVICE_GET_STRUCT_RESULT_SUCCESS:
      g_value_set_object (value, self->success);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
shared_service_get_struct_result_instance_init (SharedServiceGetStructResult * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->success = g_object_new (TYPE_SHARED_STRUCT, NULL);
  object->__isset_success = FALSE;
}

static void 
shared_service_get_struct_result_finalize (GObject *object)
{
  SharedServiceGetStructResult *tobject = SHARED_SERVICE_GET_STRUCT_RESULT (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->success != NULL)
  {
    g_object_unref(tobject->success);
    tobject->success = NULL;
  }
}

static void
shared_service_get_struct_result_class_init (SharedServiceGetStructResultClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = shared_service_get_struct_result_read;
  struct_class->write = shared_service_get_struct_result_write;

  gobject_class->finalize = shared_service_get_struct_result_finalize;
  gobject_class->get_property = shared_service_get_struct_result_get_property;
  gobject_class->set_property = shared_service_get_struct_result_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_SHARED_SERVICE_GET_STRUCT_RESULT_SUCCESS,
     g_param_spec_object ("success",
                         NULL,
                         NULL,
                         TYPE_SHARED_STRUCT,
                         G_PARAM_READWRITE));
}

GType
shared_service_get_struct_result_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (SharedServiceGetStructResultClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) shared_service_get_struct_result_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (SharedServiceGetStructResult),
      0, /* n_preallocs */
      (GInstanceInitFunc) shared_service_get_struct_result_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "SharedServiceGetStructResultType",
                                   &type_info, 0);
  }

  return type;
}

